// =============================================================================
// Import
// =============================================================================

// React
import React from 'react';

// Components
import { Link } from '../../components/Navigation/Link';

// =============================================================================
// Content
// =============================================================================

const legal = {
  top: {
    title:    'legal',
    subtitle: 'the lawyer stuff because we have to in this world.',
    text:     (
      <span>
        Copyright (c) {new Date().getFullYear()} Jan Hrubý. The content of this
        website is all rights reserved of their respective owners. The code of
        this website is licensed under the{' '}
        <Link to="https://github.com/mrozilla/mrozilla.cz/blob/master/LICENSE">
          MIT License
        </Link>.
      </span>
    ),
  },
  text: [
    <span>
      Credits: All images on the website are copyrights of their respective
      owners. The website uses {' '}
      <Link to="https://github.com/mrozilla/mrozilla.cz/blob/master/package.json">
        open-source software
      </Link>.
    </span>,
    <span>
      Liability for content: I make every effort to keep the information on my
      website current, but accept no liability whatsoever for the content
      provided. I am not obligated to monitor third party information provided
      or stored on my website. However, I shall promptly remove any content upon
      becoming aware that it violates the law. My liability in such an instance
      shall commence at the time I become aware of the respective violation.
    </span>,
    <span>
      Liability for links: This site contains links to third-party websites. I
      have no influence whatsoever on the information on these websites and
      accept no guaranty for its correctness. The content of such third-party
      sites is the responsibility of the respective owners/providers. At the
      time third-party websites were linked to mine, I found no grounds
      whatsoever of any likely contravention of the law. I shall promptly delete
      a link upon becoming aware that it violates the law.
    </span>,
    <span>
      Data protection: Please be aware that there are inherent security risks in
      transmitting data, such as emails, via the Internet, because it is
      impossible to safeguard completely against unauthorized access by third
      parties. Nevertheless, I shall safeguard your data, subject to this
      limitation. In particular, personal information will be transmitted via
      the Internet only if it does not infringe upon third-party rights, unless
      the respective party has given its prior consent in view of such security
      risks. Accordingly, as the website provider, I shall not be held liable
      for any damages incurred as a consequence of such security risks or for
      any related acts of omission on our part.I oppose the use of any available
      contact information by a third party for sending unsolicited
      advertisements. As the website provider, I reserve the express right to
      take legal action against unsolicited mailing or emailing of spam and
      other similar advertising materials.
    </span>,
    <span>
      This website uses Google Analytics, a web analytics service provided by
      Google, Inc. (&quot;Google&quot;). Google Analytics uses
      &quot;cookies&quot;, which are text files placed on your computer, to help
      the website analyze how users use the site. The information generated by
      the cookie about your use of the website (including your IP address) will
      be transmitted to and stored by Google on servers in the United States .
      Google will use this information for the purpose of evaluating your use of
      the website, compiling reports on website activity for website operators
      and providing other services relating to website activity and internet
      usage. Google may also transfer this information to third parties where
      required to do so by law, or where such third parties process the
      information on Google&apos;s behalf. Google will not associate your IP
      address with any other data held by Google. You may refuse the use of
      cookies by selecting the appropriate settings on your browser, however
      please note that if you do this you may not be able to use the full
      functionality of this website. By using this website, you consent to the
      processing of data about you by Google in the manner and for the purposes
      set out above.
    </span>,
  ],
};

export default legal;
